AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Orfanato NIB Amplify App with production and staging environments'

Parameters:
  RepositoryUrl:
    Type: String
    Description: 'GitHub repository URL'
    Default: 'https://github.com/your-org/orfanatonib-app'

  GitHubAccessToken:
    Type: String
    Description: 'GitHub Personal Access Token (Classic) para o Amplify clonar o repositório'
    NoEcho: true

  RepositoryBranch:
    Type: String
    Description: 'Main branch name'
    Default: 'main'

  StagingBranch:
    Type: String
    Description: 'Staging branch name'
    Default: 'staging'

  # Production Environment Variables
  ProdApiUrl:
    Type: String
    Description: 'Production API URL'
    Default: 'https://api.orfanatonib.com'

  ProdFeedMinisterioId:
    Type: String
    Description: 'Production Feed Ministerio ID'
    Default: 'b8d9fa5f-4942-4a5b-bdf9-e1c8d7c3126b'

  ProdGoogleClientId:
    Type: String
    Description: 'Production Google Client ID'
    Default: '135271087774-favt17acohq7ope35eu48v41mi7lbshj.apps.googleusercontent.com'

  ProdSpecialFamilyDayId:
    Type: String
    Description: 'Production Special Family Day ID'
    Default: 'a2f9913a-e123-46b2-b6f4-a4138686042f'

  # Staging Environment Variables
  StagingApiUrl:
    Type: String
    Description: 'Staging API URL'
    Default: 'https://staging-api.orfanatonib.com'

  StagingFeedMinisterioId:
    Type: String
    Description: 'Staging Feed Ministerio ID'
    Default: 'afa51053-1296-4c89-9059-a8ad8bd1ec90'

  StagingGoogleClientId:
    Type: String
    Description: 'Staging Google Client ID'
    Default: '135271087774-favt17acohq7ope35eu48v41mi7lbshj.apps.googleusercontent.com'

  StagingSpecialFamilyDayId:
    Type: String
    Description: 'Staging Special Family Day ID'
    Default: 'a2f9913a-e123-46b2-b6f4-a4138686042f'

  RootDomainName:
    Type: String
    Description: 'Domínio raiz para produção (ex: orfanatonib.com)'
    Default: 'orfanatonib.com'

  StagingSubdomainPrefix:
    Type: String
    Description: 'Prefixo do subdomínio de staging (ex: staging)'
    Default: 'staging'

  HostedZoneId:
    Type: String
    Description: 'Route53 Hosted Zone ID do domínio (opcional; se vazio, o custom resource tenta descobrir pelo nome)'
    Default: ''

Resources:
  # Amplify App
  AmplifyApp:
    Type: 'AWS::Amplify::App'
    Properties:
      Name: 'orfanatonib-app'
      Description: 'Orfanato NIB React Application'
      Repository: !Ref RepositoryUrl
      AccessToken: !Ref GitHubAccessToken
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - echo "Using Node $(node -v) before nvm..."
                - nvm install 20
                - nvm use 20
                - node -v
                - corepack enable || true
                - if [ -f package-lock.json ]; then npm ci; else npm i; fi
                - |
                  if [ -z "$VITE_API_URL" ] || [ -z "$VITE_FEED_MINISTERIO_ID" ] || [ -z "$VITE_GOOGLE_CLIENT_ID" ] || [ -z "$VITE_SPECIAL_FAMILY_DAY_ID" ]; then
                    echo "Erro: Uma ou mais variáveis de ambiente necessárias não estão definidas no Amplify Console"
                    echo "Variáveis necessárias: VITE_API_URL, VITE_FEED_MINISTERIO_ID, VITE_GOOGLE_CLIENT_ID, VITE_SPECIAL_FAMILY_DAY_ID"
                    exit 1
                  fi
                - |
                  cat > .env <<EOF
                  VITE_API_URL=$VITE_API_URL
                  VITE_FEED_MINISTERIO_ID=$VITE_FEED_MINISTERIO_ID
                  VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
                  VITE_SPECIAL_FAMILY_DAY_ID=$VITE_SPECIAL_FAMILY_DAY_ID
                  EOF
            build:
              commands:
                - echo "Iniciando build da aplicação..."
                - npm run build
                - echo "Build concluído. Verificando se os arquivos foram gerados..."
                - ls -la dist/
                - |
                  if [ ! -d "dist" ] || [ ! -f "dist/index.html" ]; then
                    echo "Erro: Build falhou - diretório dist ou index.html não encontrado"
                    exit 1
                  fi
                - echo "Build bem-sucedido! Arquivos prontos para deploy."
          artifacts:
            baseDirectory: dist
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*

  # Production Branch
  ProductionBranch:
    Type: 'AWS::Amplify::Branch'
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref RepositoryBranch
      Description: 'Production branch'
      EnableAutoBuild: true
      Stage: PRODUCTION
      EnvironmentVariables:
        - Name: 'VITE_API_URL'
          Value: !Ref ProdApiUrl
        - Name: 'VITE_FEED_MINISTERIO_ID'
          Value: !Ref ProdFeedMinisterioId
        - Name: 'VITE_GOOGLE_CLIENT_ID'
          Value: !Ref ProdGoogleClientId
        - Name: 'VITE_SPECIAL_FAMILY_DAY_ID'
          Value: !Ref ProdSpecialFamilyDayId

  # Staging Branch
  StagingBranchResource:
    Type: 'AWS::Amplify::Branch'
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref StagingBranch
      Description: 'Staging branch'
      EnableAutoBuild: true
      Stage: BETA
      EnvironmentVariables:
        - Name: 'VITE_API_URL'
          Value: !Ref StagingApiUrl
        - Name: 'VITE_FEED_MINISTERIO_ID'
          Value: !Ref StagingFeedMinisterioId
        - Name: 'VITE_GOOGLE_CLIENT_ID'
          Value: !Ref StagingGoogleClientId
        - Name: 'VITE_SPECIAL_FAMILY_DAY_ID'
          Value: !Ref StagingSpecialFamilyDayId

  DomainAssociation:
    Type: 'AWS::Amplify::Domain'
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      DomainName: !Ref RootDomainName
      SubDomainSettings:
        # Produção: domínio raiz
        - BranchName: !Ref RepositoryBranch
          Prefix: ''
        # Staging: staging.<dominio>
        - BranchName: !Ref StagingBranch
          Prefix: !Ref StagingSubdomainPrefix

  # --- Route53 DNS automation (no manual steps) ---
  AmplifyDomainDnsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: amplify-domain-dns
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - amplify:GetDomainAssociation
                Resource: "*"
              - Effect: Allow
                Action:
                  - route53:ListHostedZonesByName
                  - route53:ChangeResourceRecordSets
                  - route53:ListResourceRecordSets
                Resource: "*"

  AmplifyDomainDnsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt AmplifyDomainDnsLambdaRole.Arn
      Runtime: python3.13
      Handler: index.handler
      Timeout: 300
      MemorySize: 256
      Code:
        ZipFile: |
          import json
          import time
          import urllib.request
          import boto3

          CLOUDFRONT_ZONE_ID = "Z2FDTNDATAQYW2"

          def send(event, context, status, data=None, physical_id=None, reason=None):
              data = data or {}
              body = {
                  "Status": status,
                  "Reason": reason or f"See CloudWatch Logs: {context.log_stream_name}",
                  "PhysicalResourceId": physical_id or context.log_stream_name,
                  "StackId": event["StackId"],
                  "RequestId": event["RequestId"],
                  "LogicalResourceId": event["LogicalResourceId"],
                  "NoEcho": False,
                  "Data": data,
              }
              req = urllib.request.Request(
                  event["ResponseURL"],
                  data=json.dumps(body).encode("utf-8"),
                  headers={"content-type": ""},
                  method="PUT",
              )
              urllib.request.urlopen(req)

          def parse_cert_record(s: str):
              # format: "<name> CNAME <value>"
              parts = [p for p in s.strip().split(" ") if p]
              if len(parts) < 3:
                  return None
              name = parts[0]
              rtype = parts[1].upper()
              value = parts[2]
              if not name.endswith("."):
                  name += "."
              if not value.endswith("."):
                  value += "."
              return (name, rtype, value)

          def parse_cloudfront_target(dns_record: str):
              # examples:
              # " CNAME xyz.cloudfront.net"
              # "staging CNAME xyz.cloudfront.net"
              parts = [p for p in dns_record.strip().split(" ") if p]
              # Either 3 parts (prefix, CNAME, target) or 2 parts (CNAME, target) when prefix is blank.
              if len(parts) == 2:
                  target = parts[1]
              elif len(parts) >= 3:
                  target = parts[2]
              else:
                  return None
              if not target.endswith("."):
                  target += "."
              return target

          def find_hosted_zone_id(route53, domain_name: str):
              # domain_name in Amplify comes as "orfanatonib.com"
              dns_name = domain_name if domain_name.endswith(".") else domain_name + "."
              resp = route53.list_hosted_zones_by_name(DNSName=dns_name, MaxItems="1")
              zones = resp.get("HostedZones", [])
              if not zones:
                  return None
              z = zones[0]
              if z.get("Name") != dns_name:
                  return None
              # Id: "/hostedzone/XYZ"
              zid = z.get("Id", "").split("/")[-1]
              return zid or None

          def upsert_records(route53, hosted_zone_id: str, changes: list):
              # Changes is list of Change dicts
              route53.change_resource_record_sets(
                  HostedZoneId=hosted_zone_id,
                  ChangeBatch={"Comment": "Amplify domain association DNS (managed by CloudFormation)", "Changes": changes},
              )

          def handler(event, context):
              props = event.get("ResourceProperties", {})
              app_id = props["AppId"]
              domain_name = props["DomainName"]
              staging_prefix = props["StagingPrefix"]
              hosted_zone_id = (props.get("HostedZoneId") or "").strip()

              amplify = boto3.client("amplify")
              route53 = boto3.client("route53")

              # Discover hosted zone if not provided
              if not hosted_zone_id:
                  hosted_zone_id = find_hosted_zone_id(route53, domain_name)
              if not hosted_zone_id:
                  send(event, context, "FAILED", reason=f"HostedZoneId not found for domain {domain_name}. Provide HostedZoneId parameter.")
                  return

              # For Delete, best-effort cleanup
              if event["RequestType"] == "Delete":
                  try:
                      da = amplify.get_domain_association(appId=app_id, domainName=domain_name)["domainAssociation"]
                      cert = da.get("certificateVerificationDNSRecord") or da.get("certificate", {}).get("certificateVerificationDNSRecord") or ""
                      cert_rec = parse_cert_record(cert) if cert else None

                      target = None
                      for sd in da.get("subDomains", []):
                          if (sd.get("subDomainSetting") or {}).get("branchName") == "main":
                              target = parse_cloudfront_target(sd.get("dnsRecord",""))
                              break
                      if not target:
                          # fallback: use first subdomain
                          if da.get("subDomains"):
                              target = parse_cloudfront_target(da["subDomains"][0].get("dnsRecord",""))
                      changes = []
                      if target:
                          changes.extend([
                              {
                                  "Action": "DELETE",
                                  "ResourceRecordSet": {
                                      "Name": domain_name + ".",
                                      "Type": "A",
                                      "AliasTarget": {"HostedZoneId": CLOUDFRONT_ZONE_ID, "DNSName": target, "EvaluateTargetHealth": False},
                                  },
                              },
                              {
                                  "Action": "DELETE",
                                  "ResourceRecordSet": {
                                      "Name": domain_name + ".",
                                      "Type": "AAAA",
                                      "AliasTarget": {"HostedZoneId": CLOUDFRONT_ZONE_ID, "DNSName": target, "EvaluateTargetHealth": False},
                                  },
                              },
                              {
                                  "Action": "DELETE",
                                  "ResourceRecordSet": {
                                      "Name": f\"{staging_prefix}.{domain_name}.\",
                                      "Type": "CNAME",
                                      "TTL": 300,
                                      "ResourceRecords": [{"Value": target}],
                                  },
                              },
                          ])
                      if cert_rec:
                          name, rtype, value = cert_rec
                          changes.append({
                              "Action": "DELETE",
                              "ResourceRecordSet": {
                                  "Name": name,
                                  "Type": rtype,
                                  "TTL": 300,
                                  "ResourceRecords": [{"Value": value}],
                              },
                          })
                      if changes:
                          upsert_records(route53, hosted_zone_id, changes)
                  except Exception:
                      pass
                  send(event, context, "SUCCESS", physical_id=f\"{app_id}:{domain_name}\")
                  return

              # Create/Update: wait until Amplify has DNS records
              last = None
              for _ in range(30):
                  da = amplify.get_domain_association(appId=app_id, domainName=domain_name)["domainAssociation"]
                  last = da
                  cert = da.get("certificateVerificationDNSRecord") or da.get("certificate", {}).get("certificateVerificationDNSRecord") or ""
                  subdomains = da.get("subDomains", [])
                  if cert and subdomains:
                      break
                  time.sleep(5)

              cert = (last or {}).get("certificateVerificationDNSRecord") or (last or {}).get("certificate", {}).get("certificateVerificationDNSRecord") or ""
              cert_rec = parse_cert_record(cert) if cert else None

              # get CloudFront target from main subdomain
              target = None
              for sd in (last or {}).get("subDomains", []):
                  setting = sd.get("subDomainSetting") or {}
                  if setting.get("branchName") == "main" and not setting.get("prefix"):
                      target = parse_cloudfront_target(sd.get("dnsRecord",""))
                      break
              if not target and (last or {}).get("subDomains"):
                  target = parse_cloudfront_target((last or {})["subDomains"][0].get("dnsRecord",""))

              if not target or not cert_rec:
                  send(event, context, "FAILED", reason="Amplify domain association did not provide DNS records in time.")
                  return

              name, rtype, value = cert_rec
              apex = domain_name + "."
              staging_fqdn = f\"{staging_prefix}.{domain_name}.\"

              changes = [
                  {
                      "Action": "UPSERT",
                      "ResourceRecordSet": {
                          "Name": apex,
                          "Type": "A",
                          "AliasTarget": {"HostedZoneId": CLOUDFRONT_ZONE_ID, "DNSName": target, "EvaluateTargetHealth": False},
                      },
                  },
                  {
                      "Action": "UPSERT",
                      "ResourceRecordSet": {
                          "Name": apex,
                          "Type": "AAAA",
                          "AliasTarget": {"HostedZoneId": CLOUDFRONT_ZONE_ID, "DNSName": target, "EvaluateTargetHealth": False},
                      },
                  },
                  {
                      "Action": "UPSERT",
                      "ResourceRecordSet": {
                          "Name": staging_fqdn,
                          "Type": "CNAME",
                          "TTL": 300,
                          "ResourceRecords": [{"Value": target}],
                      },
                  },
                  {
                      "Action": "UPSERT",
                      "ResourceRecordSet": {
                          "Name": name,
                          "Type": rtype,
                          "TTL": 300,
                          "ResourceRecords": [{"Value": value}],
                      },
                  },
              ]

              upsert_records(route53, hosted_zone_id, changes)
              send(
                  event,
                  context,
                  "SUCCESS",
                  data={"HostedZoneId": hosted_zone_id, "CloudFrontTarget": target},
                  physical_id=f\"{app_id}:{domain_name}\",
              )

  AmplifyDomainDnsRecords:
    Type: Custom::AmplifyDomainDnsRecords
    DependsOn:
      - DomainAssociation
    Properties:
      ServiceToken: !GetAtt AmplifyDomainDnsLambda.Arn
      AppId: !GetAtt AmplifyApp.AppId
      DomainName: !Ref RootDomainName
      StagingPrefix: !Ref StagingSubdomainPrefix
      HostedZoneId: !Ref HostedZoneId

Outputs:
  AmplifyAppId:
    Description: 'Amplify App ID'
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Sub '${AWS::StackName}-AppId'

  ProductionBranchName:
    Description: 'Production branch name'
    Value: !Ref RepositoryBranch
    Export:
      Name: !Sub '${AWS::StackName}-ProductionBranch'

  StagingBranchName:
    Description: 'Staging branch name'
    Value: !Ref StagingBranchResource
    Export:
      Name: !Sub '${AWS::StackName}-StagingBranch'

  ProductionDomain:
    Description: 'Production domain URL'
    Value: !Sub 'https://${RootDomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-ProductionDomain'

  StagingDomain:
    Description: 'Staging domain URL'
    Value: !Sub 'https://${StagingSubdomainPrefix}.${RootDomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-StagingDomain'
